const COMPONENT_DOUBLE_CHECKS = [
  "NAME",
  "ORDER_NUMBER",
  "RESULT_TYPE",
  "UNITS",
  "USES_INSTRUMENT",
  "AUTO_CALC",
  "ALIAS_NAME",
  "HAS_ATTRIBUTES",
  "FORMAT_CALCULATION",
  "C_EMP_FORMULA_MAP",
];

export default COMPONENT_DOUBLE_CHECKS;
