const PRODUCT_SPEC_MANUALS = [
  "ROUND",
  "PLACES",
  "NUM_RESULT_REPS",
  "HI_CONTROL_1",
  "LO_CONTROL_1",
  "T_PH_PROD_COMPOUND",
  "T_DISS_TIMEPOINT",
  "C_LOD_LIMIT",
  "C_LOQ_LIMIT",
  "C_EMP_COMP_NAME",
  "C_INV_WT_MAP",
  "C_VALIDITY_WT",
  "C_EQUIV_WEIGHT",
];

export default PRODUCT_SPEC_MANUALS;
