const SAMPLING_POINT_OPTIONS = [
  "RELEASE",
  "VALIDATION",
  "STABILITY",
  "REAGENTS",
  "NONE",
  "HOLDTIMESTUDY",
  "DAILY",
  "LEACHABLE",
  "VS",
  "MONTHLY",
  "MONITORING",
  "SP001",
  "INNOVATOR",
  "RELEASE_MIXED_SAMPLE",
  "CALIBRATION",
];

export default SAMPLING_POINT_OPTIONS;
